# Use an official Python image
FROM python:3.12-slim

# Install Poetry
RUN pip install poetry

# Set the working directory
WORKDIR /app

# # Copy pyproject.toml and poetry.lock
# COPY pyproject.toml poetry.lock /app/
# Copy only pyproject.toml
COPY pyproject.toml /app/


# Install dependencies
RUN poetry config virtualenvs.create false && poetry install --no-dev

# Copy the FastAPI app code
COPY . /app

# Expose port for FastAPI
EXPOSE 8000

# Run FastAPI
CMD ["uvicorn", "api_Final:app", "--host", "0.0.0.0", "--port", "8000"]
